APPLY_FIXES: all
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
TYPESCRIPT_DEFAULT_STYLE: prettier
DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_ES
  - YAML_YAMLLINT
IGNORE_GENERATED_FILES: true
FILTER_REGEX_EXCLUDE: pnpm-lock\.yaml
SPELL_CSPELL_FILE_EXTENSIONS:
  - .md
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: \.md$
REPOSITORY_DEVSKIM_ARGUMENTS:
  - -g
  - '**/.git/**,**/node_modules/**,**/pnpm-lock.yaml'
TYPESCRIPT_ES_CLI_LINT_MODE: project
